//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebService.MyWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="makoff.webService", ConfigurationName="MyWebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name oX from namespace makoff.webService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="makoff.webService/WalidacjaInt", ReplyAction="*")]
        TestWebService.MyWebService.WalidacjaIntResponse WalidacjaInt(TestWebService.MyWebService.WalidacjaIntRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="makoff.webService/Dodaj", ReplyAction="*")]
        int Dodaj(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="makoff.webService/Odejmij", ReplyAction="*")]
        int Odejmij(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="makoff.webService/Pomnoz", ReplyAction="*")]
        int Pomnoz(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="makoff.webService/Podziel", ReplyAction="*")]
        int Podziel(int x, int y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WalidacjaIntRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WalidacjaInt", Namespace="makoff.webService", Order=0)]
        public TestWebService.MyWebService.WalidacjaIntRequestBody Body;
        
        public WalidacjaIntRequest() {
        }
        
        public WalidacjaIntRequest(TestWebService.MyWebService.WalidacjaIntRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="makoff.webService")]
    public partial class WalidacjaIntRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object oX;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object oY;
        
        public WalidacjaIntRequestBody() {
        }
        
        public WalidacjaIntRequestBody(object oX, object oY) {
            this.oX = oX;
            this.oY = oY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WalidacjaIntResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WalidacjaIntResponse", Namespace="makoff.webService", Order=0)]
        public TestWebService.MyWebService.WalidacjaIntResponseBody Body;
        
        public WalidacjaIntResponse() {
        }
        
        public WalidacjaIntResponse(TestWebService.MyWebService.WalidacjaIntResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="makoff.webService")]
    public partial class WalidacjaIntResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool WalidacjaIntResult;
        
        public WalidacjaIntResponseBody() {
        }
        
        public WalidacjaIntResponseBody(bool WalidacjaIntResult) {
            this.WalidacjaIntResult = WalidacjaIntResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : TestWebService.MyWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<TestWebService.MyWebService.WebServiceSoap>, TestWebService.MyWebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebService.MyWebService.WalidacjaIntResponse TestWebService.MyWebService.WebServiceSoap.WalidacjaInt(TestWebService.MyWebService.WalidacjaIntRequest request) {
            return base.Channel.WalidacjaInt(request);
        }
        
        public bool WalidacjaInt(object oX, object oY) {
            TestWebService.MyWebService.WalidacjaIntRequest inValue = new TestWebService.MyWebService.WalidacjaIntRequest();
            inValue.Body = new TestWebService.MyWebService.WalidacjaIntRequestBody();
            inValue.Body.oX = oX;
            inValue.Body.oY = oY;
            TestWebService.MyWebService.WalidacjaIntResponse retVal = ((TestWebService.MyWebService.WebServiceSoap)(this)).WalidacjaInt(inValue);
            return retVal.Body.WalidacjaIntResult;
        }
        
        public int Dodaj(int x, int y) {
            return base.Channel.Dodaj(x, y);
        }
        
        public int Odejmij(int x, int y) {
            return base.Channel.Odejmij(x, y);
        }
        
        public int Pomnoz(int x, int y) {
            return base.Channel.Pomnoz(x, y);
        }
        
        public int Podziel(int x, int y) {
            return base.Channel.Podziel(x, y);
        }
    }
}
